name: main
# To trigger on every push on any branch
on: push
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu_latest
    steps:
    - name: running single command in job
      run: echo "This is my first GitHub workflow"
    - name: checking Os release for GitHub runner
      run: cat /etc/os-release

      
      
    
      
      
      run: 
      
      
    
    

    
    

